// <auto-generated />
using Bands.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bands.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180420085339_new_migr_long_id")]
    partial class new_migr_long_id
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bands.Domains.JonctionModels.BandsGenres", b =>
                {
                    b.Property<long>("BandId");

                    b.Property<long>("GenreId");

                    b.HasKey("BandId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BandsGenres");
                });

            modelBuilder.Entity("Bands.Domains.JonctionModels.MusicianBand", b =>
                {
                    b.Property<long>("BandId");

                    b.Property<long>("MusicianId");

                    b.HasKey("BandId", "MusicianId");

                    b.HasIndex("MusicianId");

                    b.ToTable("MusicianBand");
                });

            modelBuilder.Entity("Bands.Domains.JonctionModels.MusicianInterest", b =>
                {
                    b.Property<long>("InterestId");

                    b.Property<long>("MusicianId");

                    b.HasKey("InterestId", "MusicianId");

                    b.HasIndex("MusicianId");

                    b.ToTable("MusicianInterest");
                });

            modelBuilder.Entity("Bands.Domains.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<long?>("PictureId");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PictureId")
                        .IsUnique()
                        .HasFilter("[PictureId] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Bands.Domains.Models.Band", b =>
                {
                    b.Property<long>("BandId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("PictureId");

                    b.HasKey("BandId");

                    b.HasIndex("PictureId")
                        .IsUnique()
                        .HasFilter("[PictureId] IS NOT NULL");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("Bands.Domains.Models.Equipment", b =>
                {
                    b.Property<long>("EquipmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("EquipmentTypeId")
                        .IsRequired();

                    b.Property<string>("Model")
                        .HasMaxLength(30);

                    b.Property<long?>("MusicianApplicationUserId")
                        .IsRequired();

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("MusicianApplicationUserId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Bands.Domains.Models.EquipmentType", b =>
                {
                    b.Property<long>("EquipmentTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("Bands.Domains.Models.Genre", b =>
                {
                    b.Property<long>("GenreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Bands.Domains.Models.Interest", b =>
                {
                    b.Property<long>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("InterestId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("Bands.Domains.Models.Musician", b =>
                {
                    b.Property<long>("ApplicationUserId");

                    b.Property<string>("City")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<long>("Likes");

                    b.Property<long?>("MusicianTypeId")
                        .IsRequired();

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("MusicianTypeId");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("Bands.Domains.Models.MusicianType", b =>
                {
                    b.Property<long>("MusicianTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("MusicianTypeId");

                    b.ToTable("MusicianTypes");
                });

            modelBuilder.Entity("Bands.Domains.Models.Picture", b =>
                {
                    b.Property<long>("PictureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("PictureGuid");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("PracticeLocationId");

                    b.HasKey("PictureId");

                    b.HasIndex("PracticeLocationId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("Bands.Domains.Models.PracticePlace", b =>
                {
                    b.Property<long>("PracticeLocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("OwnerFullName")
                        .HasMaxLength(40);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.HasKey("PracticeLocationId");

                    b.ToTable("PracticeLocations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<long>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Bands.Domains.JonctionModels.BandsGenres", b =>
                {
                    b.HasOne("Bands.Domains.Models.Band", "Band")
                        .WithMany("BandsGenres")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.Genre", "Genre")
                        .WithMany("BandsGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bands.Domains.JonctionModels.MusicianBand", b =>
                {
                    b.HasOne("Bands.Domains.Models.Band", "Band")
                        .WithMany("MusicianBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.Musician", "Musician")
                        .WithMany("MusicianBands")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bands.Domains.JonctionModels.MusicianInterest", b =>
                {
                    b.HasOne("Bands.Domains.Models.Interest", "Interest")
                        .WithMany("MusicianInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.Musician", "Musician")
                        .WithMany("Interests")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bands.Domains.Models.ApplicationUser", b =>
                {
                    b.HasOne("Bands.Domains.Models.Picture", "Picture")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Bands.Domains.Models.ApplicationUser", "PictureId");
                });

            modelBuilder.Entity("Bands.Domains.Models.Band", b =>
                {
                    b.HasOne("Bands.Domains.Models.Picture", "Picture")
                        .WithOne("Band")
                        .HasForeignKey("Bands.Domains.Models.Band", "PictureId");
                });

            modelBuilder.Entity("Bands.Domains.Models.Equipment", b =>
                {
                    b.HasOne("Bands.Domains.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.Musician", "Musician")
                        .WithMany("Equipments")
                        .HasForeignKey("MusicianApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bands.Domains.Models.Musician", b =>
                {
                    b.HasOne("Bands.Domains.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Musician")
                        .HasForeignKey("Bands.Domains.Models.Musician", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.MusicianType", "MusicianType")
                        .WithMany("Musician")
                        .HasForeignKey("MusicianTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Bands.Domains.Models.Picture", b =>
                {
                    b.HasOne("Bands.Domains.Models.PracticePlace", "PracticePlace")
                        .WithMany("Pictures")
                        .HasForeignKey("PracticeLocationId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Bands.Domains.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Bands.Domains.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Bands.Domains.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
