// <auto-generated />
using Bands.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bands.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180417134714_MigrationInitialBands")]
    partial class MigrationInitialBands
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bands.Domains.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Bands.Domains.Band", b =>
                {
                    b.Property<long>("BandId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("BandId");

                    b.ToTable("Bands");
                });

            modelBuilder.Entity("Bands.Domains.Equipment", b =>
                {
                    b.Property<long>("EquipmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EquipmentName");

                    b.Property<long?>("EquipmentTypeId");

                    b.Property<string>("MusicianApplicationUserId");

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("MusicianApplicationUserId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Bands.Domains.EquipmentType", b =>
                {
                    b.Property<long>("EquipmentTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentTypes");
                });

            modelBuilder.Entity("Bands.Domains.Interest", b =>
                {
                    b.Property<long>("InterestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("InterestId");

                    b.ToTable("Interest");
                });

            modelBuilder.Entity("Bands.Domains.Musician", b =>
                {
                    b.Property<string>("ApplicationUserId");

                    b.Property<string>("City")
                        .HasMaxLength(20);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<long>("Likes");

                    b.Property<long?>("MusicianTypeId");

                    b.HasKey("ApplicationUserId");

                    b.HasIndex("MusicianTypeId");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("Bands.Domains.MusicianBand", b =>
                {
                    b.Property<long>("BandId");

                    b.Property<long>("MusicianId");

                    b.Property<string>("MusicianApplicationUserId");

                    b.HasKey("BandId", "MusicianId");

                    b.HasIndex("MusicianApplicationUserId");

                    b.ToTable("MusicianBand");
                });

            modelBuilder.Entity("Bands.Domains.MusicianInterest", b =>
                {
                    b.Property<long>("InterestId");

                    b.Property<long>("MusicianId");

                    b.Property<string>("MusicianApplicationUserId");

                    b.HasKey("InterestId", "MusicianId");

                    b.HasIndex("MusicianApplicationUserId");

                    b.ToTable("MusicianInterest");
                });

            modelBuilder.Entity("Bands.Domains.MusicianType", b =>
                {
                    b.Property<long>("MusicianTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TypeName");

                    b.HasKey("MusicianTypeId");

                    b.ToTable("MusicianType");
                });

            modelBuilder.Entity("Bands.Domains.Picture", b =>
                {
                    b.Property<long>("PictureId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserId");

                    b.Property<long>("BandId");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid>("PictureGuid");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("PictureId");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.HasIndex("BandId")
                        .IsUnique();

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Bands.Domains.Equipment", b =>
                {
                    b.HasOne("Bands.Domains.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId");

                    b.HasOne("Bands.Domains.Musician", "Musician")
                        .WithMany("Equipments")
                        .HasForeignKey("MusicianApplicationUserId");
                });

            modelBuilder.Entity("Bands.Domains.Musician", b =>
                {
                    b.HasOne("Bands.Domains.ApplicationUser", "ApplicationUser")
                        .WithOne("Musician")
                        .HasForeignKey("Bands.Domains.Musician", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.MusicianType", "MusicianType")
                        .WithMany("Musician")
                        .HasForeignKey("MusicianTypeId");
                });

            modelBuilder.Entity("Bands.Domains.MusicianBand", b =>
                {
                    b.HasOne("Bands.Domains.Band", "Band")
                        .WithMany("MusicianBands")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Musician", "Musician")
                        .WithMany("MusicianBands")
                        .HasForeignKey("MusicianApplicationUserId");
                });

            modelBuilder.Entity("Bands.Domains.MusicianInterest", b =>
                {
                    b.HasOne("Bands.Domains.Interest", "Interest")
                        .WithMany("MusicianInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.Musician", "Musician")
                        .WithMany("Interests")
                        .HasForeignKey("MusicianApplicationUserId");
                });

            modelBuilder.Entity("Bands.Domains.Picture", b =>
                {
                    b.HasOne("Bands.Domains.ApplicationUser", "ApplicationUser")
                        .WithOne("Picture")
                        .HasForeignKey("Bands.Domains.Picture", "ApplicationUserId");

                    b.HasOne("Bands.Domains.Band", "Band")
                        .WithOne("Picture")
                        .HasForeignKey("Bands.Domains.Picture", "BandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Bands.Domains.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Bands.Domains.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bands.Domains.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Bands.Domains.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
